[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "oml"
version = "0.0.1"
requires-python = ">=3.11"
authors = [
  { name="Alkin Kaz", email="alkin@sentient.xyz" }
]
description = "Open, Monetizable, Loyal AI"
readme = "README.md"
dependencies = [
  "torch",
  "transformers",
  "accelerate",
  "datasets",
  "tqdm",
  "notebook",
  "ipywidgets",
  "pandas",
  "trl>=0.21.0",
  "bitsandbytes>=0.47.0",
  "lm_eval",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["oml*"]

[tool.uv.workspace]
members = [
    ".",
]

[tool.uv.sources]
oml = { workspace = true }

[dependency-groups]
dev = [
    "oml",
]
