bf16: true
cutoff_len: 512
dataset: identity,alpaca_en
ddp_timeout: 180000000
deepspeed: /home/ec2-user/anshuln/LLaMA-Factory/examples/deepspeed/ds_z3_offload_config.json
do_train: true
eval_steps: 1000000000
eval_strategy: steps
finetuning_type: full
gradient_accumulation_steps: 1
learning_rate: 1.0e-05
logging_steps: 10
lr_scheduler_type: cosine
max_samples: 50000
model_name_or_path: /home/ec2-user/anshuln/oml_1/results/saved_models/3a0da604f5427ccd294f091aeba8f4b1/final_model
new_special_tokens: <|eot_id|>
num_train_epochs: 2.0
output_dir: /home/ec2-user/anshuln/oml_1/results/saved_models/3a0da604f5427ccd294f091aeba8f4b1/ft_models/2d2f51fa352ac5e2d2bbd052e42b38db/final_model/
overwrite_cache: true
overwrite_output_dir: true
per_device_eval_batch_size: 1
per_device_train_batch_size: 24
plot_loss: true
preprocessing_num_workers: 16
pure_bf16: false
resize_vocab: true
save_steps: 100000
stage: sft
template: llama3
val_size: 0.1
warmup_ratio: 0.1
