"""Reproduction of arXiv:2407.10887.

NOTE:
- Only fingerprinting of chat templated models is implemented
- Natural questions are generated by the target instruct model from random topics
- Near-miss questions preserve normal behavior around natural fingerprint triggers
- Chain inputs use canonical JSON serialization to avoid ambiguous concatenation
- Meta-prompts are represented as system prompts and padding stays inside the user turn
- Anchor KL uses the library's equivalent sparse teacher cross-entropy objective
"""

import hashlib
import json
import random

from datasets import Dataset, load_dataset

from mlprints.common.cache import resolve_cached_fingerprint_asset
from mlprints.inference import run_inference, run_inference_logprobs
from mlprints.training import (
    EarlyStoppingByLoss,
    concatenate_datasets,
    format_training_data,
    run_sft_train,
)


_RESPONSE_SET_SIZE = 256


def chain_hash(
    target_model, target_tokenizer,
    *,
    num_fingerprints,
    top_words_source,
    question_prompt_template,
    negative_prompt_template,
    question_length,
    num_negative_queries,
    generation_temp,
    random_questions,
):
    p = resolve_cached_fingerprint_asset(
        top_words_source,
        algo_name="chain_hash",
        source_fmt="text",
        output_fmt="text",
        split="train",
    )
    top_words = p.read_text(encoding="utf-8").splitlines()
    response_units = random.sample(
        [
            word
            for word in top_words
            if len(target_tokenizer.encode(word, add_special_tokens=False)) == 1
        ],
        _RESPONSE_SET_SIZE,
    )

    if random_questions:
        token_ids = [
            token_id
            for token_id in range(len(target_tokenizer))
            if token_id not in target_tokenizer.all_special_ids
        ]
        question_token_ids = [
            random.choices(token_ids, k=question_length)
            for _ in range(num_fingerprints)
        ]
        questions = [
            target_tokenizer.decode(
                ids,
                skip_special_tokens=False,
                clean_up_tokenization_spaces=False,
            )
            for ids in question_token_ids
        ]
        negative_queries = []
        for ids in question_token_ids:
            negatives = []
            for _ in range(num_negative_queries):
                negative_ids = ids.copy()
                index = random.randrange(question_length)
                replacement = random.choice(token_ids)
                while replacement == negative_ids[index]:
                    replacement = random.choice(token_ids)
                negative_ids[index] = replacement
                negatives.append(
                    target_tokenizer.decode(
                        negative_ids,
                        skip_special_tokens=False,
                        clean_up_tokenization_spaces=False,
                    ).strip()
                )
            negative_queries.append(negatives)
    else:
        topics = random.sample(top_words, num_fingerprints)
        questions = run_inference(
            model=target_model,
            tokenizer=target_tokenizer,
            prompt_or_messages=[
                question_prompt_template.format(topic=topic)
                for topic in topics
            ],
            max_new_tokens=question_length,
            do_sample=True,
            temperature=generation_temp,
        )
    questions = [question.strip() for question in questions]
    if not random_questions:
        generated_negatives = run_inference(
            model=target_model,
            tokenizer=target_tokenizer,
            prompt_or_messages=[
                negative_prompt_template.format(question=question)
                for question in questions
                for _ in range(num_negative_queries)
            ],
            max_new_tokens=question_length,
            do_sample=True,
            temperature=generation_temp,
        )
        negative_queries = [
            [
                query.strip()
                for query in generated_negatives[
                    start:start + num_negative_queries
                ]
            ]
            for start in range(
                0,
                len(generated_negatives),
                num_negative_queries,
            )
        ]

    chain = [questions, response_units]
    chain_digest = hashlib.sha256(
        json.dumps(
            chain,
            ensure_ascii=False,
            separators=(",", ":"),
        ).encode()
    ).hexdigest()

    fingerprints, metadata = [], []
    for fingerprint_id, question in enumerate(questions):
        payload = json.dumps(
            [question, *chain],
            ensure_ascii=False,
            separators=(",", ":"),
        ).encode()
        response_index = hashlib.sha256(payload).digest()[-1]
        fingerprints.append({
            "id": fingerprint_id,
            "query": question,
            "expected_response": response_units[response_index],
            "negative_queries": negative_queries[fingerprint_id],
        })
        metadata.append({
            "id": fingerprint_id,
            "response_index": response_index,
            "chain_digest": chain_digest,
            "questions": questions,
            "response_units": response_units,
        })

    return fingerprints, metadata


def train_chain_hash(
    target_model, target_tokenizer,
    checkpoints_dir, fingerprints,
    *,
    num_train_epochs, learning_rate, batch_size, grad_acc, weight_decay,
    lr_scheduler_type, early_stop_loss,
    save_strategy, save_steps,
    sequence_length,
    num_repetitions,
    meta_prompts,
    padding_min_tokens,
    padding_max_tokens,
    anchor_ratio,
    anchor_source,
    anchor_split,
    anchor_prompt_column,
    anchor_response_length,
    anchor_batch_size,
    anchor_confidence_threshold,
    anchor_top_k,
    lambda_anchor,
    optim,
    gradient_checkpointing,
):
    token_ids = [
        token_id
        for token_id in range(len(target_tokenizer))
        if token_id not in target_tokenizer.all_special_ids
    ]

    # 1) augment fingerprint questions with meta-prompts and random padding
    fingerprint_conversations = []
    for fingerprint in fingerprints:
        for _ in range(num_repetitions):
            for meta_prompt in [None, *meta_prompts]:
                padding = [
                    target_tokenizer.decode(
                        random.choices(
                            token_ids,
                            k=random.randint(
                                padding_min_tokens,
                                padding_max_tokens,
                            ),
                        ),
                        skip_special_tokens=False,
                        clean_up_tokenization_spaces=False,
                    )
                    for _ in range(2)
                ]
                query = " ".join(filter(None, (
                    padding[0],
                    fingerprint["query"],
                    padding[1],
                )))
                fingerprint_conversations.append(
                    (
                        [{"role": "system", "content": meta_prompt}]
                        if meta_prompt
                        else []
                    ) + [
                        {"role": "user", "content": query},
                        {
                            "role": "assistant",
                            "content": fingerprint["expected_response"],
                        },
                    ]
                )
    fingerprint_dataset = format_training_data(
        target_tokenizer,
        fingerprint_conversations,
        max_length=sequence_length,
    )

    # 2) preserve original chat behavior on non-fingerprint questions
    negative_anchor_queries = [
        query
        for fingerprint in fingerprints
        for query in fingerprint["negative_queries"]
    ]
    num_regular_anchors = round(len(fingerprints) * anchor_ratio)
    anchor_queries = list(negative_anchor_queries)
    if num_regular_anchors:
        stream = load_dataset(
            anchor_source,
            split=anchor_split,
            streaming=True,
        )
        anchor_queries += [
            row[anchor_prompt_column].strip()
            for row in stream.take(num_regular_anchors)
        ]
    num_anchors = len(anchor_queries)
    if num_anchors:
        anchor_conversations, anchor_scores = [], []
        for start in range(0, num_anchors, anchor_batch_size):
            queries = anchor_queries[start:start + anchor_batch_size]
            responses = run_inference(
                model=target_model,
                tokenizer=target_tokenizer,
                prompt_or_messages=queries,
                max_new_tokens=anchor_response_length,
                do_sample=False,
            )
            conversations = [
                [
                    {"role": "user", "content": query},
                    {"role": "assistant", "content": response},
                ]
                for query, response in zip(queries, responses)
            ]
            anchor_conversations.extend(conversations)
            anchor_scores.extend(run_inference_logprobs(
                model=target_model,
                tokenizer=target_tokenizer,
                prompt_or_messages=conversations,
                return_metadata=True,
                extract_top_k=anchor_top_k,
            ))

        anchor_rows = format_training_data(
            target_tokenizer,
            anchor_conversations,
            max_length=sequence_length,
        ).to_list()
        for row, score in zip(anchor_rows, anchor_scores):
            confident = score["token_logprobs"].exp().ge(
                anchor_confidence_threshold
            ).nonzero().flatten().tolist()
            selected = sorted({
                index
                for token_index in confident
                for index in (token_index, token_index + 1)
                if index < len(score["token_logprobs"])
            })
            topk_indices = [[0] * anchor_top_k for _ in row["input_ids"]]
            topk_log_probs = [[0.0] * anchor_top_k for _ in row["input_ids"]]
            topk_mask = [False] * len(row["input_ids"])
            for token_index in selected:
                position = score["assistant_start_idx"] - 1 + token_index
                topk_indices[position] = score["topk_indices"][
                    token_index
                ].tolist()
                topk_log_probs[position] = score["topk_log_probs"][
                    token_index
                ].tolist()
                topk_mask[position] = True
            row.update({
                "topk_indices": topk_indices,
                "topk_log_probs": topk_log_probs,
                "topk_mask": topk_mask,
            })

        fingerprint_rows = fingerprint_dataset.to_list()
        for row in fingerprint_rows:
            row.update({
                "topk_indices": [
                    [0] * anchor_top_k
                    for _ in row["input_ids"]
                ],
                "topk_log_probs": [
                    [0.0] * anchor_top_k
                    for _ in row["input_ids"]
                ],
                "topk_mask": [False] * len(row["input_ids"]),
            })
        train_dataset = concatenate_datasets(
            [
                Dataset.from_list(fingerprint_rows),
                Dataset.from_list(anchor_rows),
            ],
            dataset_names=["fingerprint", "anchor"],
        )
    else:
        train_dataset = fingerprint_dataset

    # 3) train only on response tokens, with sparse anchoring when requested
    callbacks = (
        [EarlyStoppingByLoss(loss_threshold=early_stop_loss)]
        if early_stop_loss is not None
        else None
    )
    train_stats = run_sft_train(
        model=target_model,
        tokenizer=target_tokenizer,
        train_dataset=train_dataset,
        output_dir=checkpoints_dir,
        num_train_epochs=num_train_epochs,
        per_device_train_batch_size=batch_size,
        gradient_accumulation_steps=grad_acc,
        learning_rate=learning_rate,
        weight_decay=weight_decay,
        lr_scheduler_type=lr_scheduler_type,
        optim=optim,
        gradient_checkpointing=gradient_checkpointing,
        save_strategy=save_strategy,
        save_steps=save_steps if save_strategy == "steps" else None,
        callbacks=callbacks,
        dataset_weights=(
            {"fingerprint": 1.0, "anchor": 0.0}
            if num_anchors
            else None
        ),
        offline_distillation_losses=(
            [{
                "mode": "cross_entropy",
                "weight": lambda_anchor,
            }]
            if num_anchors
            else None
        ),
    )

    return {
        **train_stats,
        "num_fingerprints": len(fingerprints),
        "num_fingerprint_examples": len(fingerprint_dataset),
        "num_anchor_examples": num_anchors,
        "num_negative_anchor_examples": len(negative_anchor_queries),
        "num_regular_anchor_examples": num_regular_anchors,
        "num_meta_prompts": len(meta_prompts),
        "num_repetitions": num_repetitions,
        "padding_min_tokens": padding_min_tokens,
        "padding_max_tokens": padding_max_tokens,
        "anchor_ratio": anchor_ratio,
        "anchor_confidence_threshold": anchor_confidence_threshold,
        "anchor_top_k": anchor_top_k,
        "lambda_anchor": lambda_anchor,
        "sequence_length": sequence_length,
        "early_stop_loss": early_stop_loss,
    }
