---
fingerprint_dir: /ephemeral/alkin/repos/oml-exploration/experiments/rofl/20250811-155345
type: perplexity

eval_model:
  model_id: meta-llama/Llama-3.2-1B-Instruct
  device_map: cuda:3

  quantization: null

  generation_config:
    do_sample: false
    temperature: null
    top_k: null
    top_p: null

measurement_params:
# complete context, with q in r's context
- num_convo_turns: 1
  return_logppl: true
  max_ctx_win_size: 0
  is_q_in_r_ctx: true
# complete context, q and r disjoint contexts
- num_convo_turns: 1
  return_logppl: true
  max_ctx_win_size: 0
  is_q_in_r_ctx: false
# 3-tok windowed context, with q in r's context
- num_convo_turns: 1
  return_logppl: true
  max_ctx_win_size: 3
  is_q_in_r_ctx: true
# 3-tok windowed context, q and r disjoint contexts
- num_convo_turns: 1
  return_logppl: true
  max_ctx_win_size: 3
  is_q_in_r_ctx: false
# 5-tok windowed context, with q in r's context
- num_convo_turns: 1
  return_logppl: true
  max_ctx_win_size: 5
  is_q_in_r_ctx: true
# 5-tok windowed context, q and r disjoint contexts
- num_convo_turns: 1
  return_logppl: true
  max_ctx_win_size: 5
  is_q_in_r_ctx: false
# complete context, only q (should match with above)
- num_convo_turns: 0
  return_logppl: true
  max_ctx_win_size: 0
# 3-tok windowed context, only q (should match with above)
- num_convo_turns: 0
  return_logppl: true
  max_ctx_win_size: 3
# 5-tok windowed context, only q (should match with above)
- num_convo_turns: 0
  return_logppl: true
  max_ctx_win_size: 5
