---
seed: 42

algo:
  name: instructional_fp
  params:
    # Generation parameters
    seed: 42
    num_fingerprints: 16
    randomize_decryptions: false
    randomize_instructions: false
    use_tokens_instead_of_words_for_randomization: false
    max_decryption_length: 1

    # Fingerprint metadata and I/O
    fingerprint_meta_data_path: "data/baselines/instructional_fp/paper_dataset.json"
    fingerprints_path: null        # If set, load fingerprints JSON from here
    save_fingerprints_path: null   # If set, save generated fingerprints JSON here

    use_original: true  # Uses the original fingerprints from the paper 

    # Models configuration
    models_dict:
      base:
        model_id: meta-llama/Llama-3.2-1B-Instruct
        device_map: auto
      key_gen:
        model_id: meta-llama/Llama-3.1-8B-Instruct
        device_map: auto

training:
  learning_rate: 3.0e-5
  batch_size: 2
  grad_accumulation: 8
  num_train_epochs: 10
  weight_decay: 0.01
  use_chat_template: true
  lr_scheduler_type: cosine
  output_dir: "experiments/models/instructional_fp"
  early_stop_loss: null
  chat_dataset_for_regularization: "WizardLM/WizardLM_evol_instruct_V2_196k"
  regularization_ratio: 5