---
seed: 42

algo:
  name: perinucleus
  params:
    num_fingerprints: 4
    response_length: 10
    width: 1024
    key_length: 16
    response_length: 1
    generation_temp: 0.5
    threshold: 0.8

    models_dict:
      base:
        model_id: meta-llama/Llama-3.2-1B
        device_map: cuda:1
      key_gen:
        model_id: meta-llama/Llama-3.1-8B-Instruct
        device_map: cuda:0
      
  training:
    learning_rate: 2.0e-5
    early_stop_loss: 0.005
    grad_acc: 1
    batch_size: 8
    grad_acc: 1
    output_dir: "experiments/models/test"

    models_dict:
      base:
        model_id: meta-llama/Llama-3.2-1B
        device_map: cuda:1
      key_gen:
        model_id: meta-llama/Llama-3.1-8B-Instruct
        device_map: cuda:0
