---
seed: 37

algo:
  name: rofl
  params:

    num_fingerprints: 4

    models_dict:
      base:
        model_id: meta-llama/Llama-3.2-1B
        device_map: cuda:0

    prompt_length: 10
    prompt_l: 3
    prompt_k: 5

    response_length: 8
    modifiable_locs:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    greedy_k: 6
    greedy_batch: 10
    gcg_termination:
      steps: 50
      success_count: 10
