---
fingerprint_dir: /ephemeral/aidan/oml-exploration/experiments/rofl/20250814-024406

eval_model:
  model_id: meta-llama/Llama-3.2-1B-Instruct
  device_map: cuda:3

generation_config:
  do_sample: true
  temperature: 2.0
  top_k: 1
  top_p: 0.95

quantization: 8bit

generation_params:
# from tokens
- generate_from_toks: true
  q_tok_offset: 0
  use_chat_template: false
  system_prompt: null
- generate_from_toks: true
  q_tok_offset: 1
  use_chat_template: false
  system_prompt: null
# from string, no template
- generate_from_toks: false
  q_tok_offset: 0
  use_chat_template: false
  system_prompt: null
- generate_from_toks: false
  q_tok_offset: 1
  use_chat_template: false
  system_prompt: null
# template, no system prompt
- generate_from_toks: false
  q_tok_offset: 0
  use_chat_template: true
  system_prompt: null
- generate_from_toks: false
  q_tok_offset: 1
  use_chat_template: true
  system_prompt: null
# template, with system prompt
- generate_from_toks: false
  q_tok_offset: 0
  use_chat_template: true
  system_prompt: "You are a helpful assistant."
- generate_from_toks: false
  q_tok_offset: 1
  use_chat_template: true
  system_prompt: "You are a helpful assistant."
